name: "Basic ticket"
description: "Minimal issue form that auto-adds to personal Project #1."
title: "[TODO] "
labels: []
assignees: []
projects:
  - "proustibat/1"
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "What should happen?"
      placeholder: "Clear, action-oriented sentence."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context / Notes
      description: "Optional supporting details, links, or screenshots."
      placeholder: "Links, hypothesis, acceptance criteria."
    validations:
      required: false
