name: 🐞 Bug
description: Something is not working as expected
title: "[Bug] "
labels: ["bug"]
assignees: []
projects:
  - "proustibat/1"
body:
  - type: markdown
    attributes:
      value: |
        <!-- Thanks for reporting a bug! Short and clear is perfect 👍 -->

  - type: textarea
    id: problem
    attributes:
      label: What is wrong?
      description: Describe what is not working.
      placeholder: A short description of the issue.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: Where does the issue happen?
      options:
        - label: Pre-production
        - label: Production
    validations:
      required: true
